const projectsDetails = [
    {
        projectName: "Wordpress Website Redesign 1",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 2",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 3",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 4",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 5",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 6",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 7",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 8",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 9",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 10",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 11",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 12",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 13",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 14",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 15",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 16",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 17",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 18",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 19",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 20",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 21",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 22",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 23",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
    {
        projectName: "Wordpress Website Redesign 24",
        date: "Apr 02, 2024",
        category: "IT, Web and Mobile",
        subCategory: "Web & Mobile Design",
        description: "We are looking for a talented Wordpress designer to redesign our existing website. The current website needs a fresh and modern look to enhance user experience and increase conversions. The successful...more",
        budget: "400",
        budgetINR: "34000",
        location: "Guam",
    },
];

export default projectsDetails;